export const ActionTypes = Object.freeze({
    USER_LOGIN_REQUEST: 'USER_LOGIN_REQUEST',
    USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
    USER_LOGIN_FAILURE: 'USER_LOGIN_FAILURE',
    //------------------------------------------------
    MESSAGE_CREATION_REQUEST: 'MESSAGE_CREATION_REQUEST',
    MESSAGE_CREATION_SUCCESS: 'MESSAGE_CREATION_SUCCESS',
    MESSAGE_CREATION_FAILURE: 'MESSAGE_CREATION_FAILURE',
    //------------------------------------------------
    MESSAGE_LIST_UPDATE_AUTO: 'MESSAGE_LIST_UPDATE_AUTO',
    //------------------------------------------------
    MESSAGE_LIST_UPDATE_REQUEST: 'MESSAGE_LIST_UPDATE_REQUEST',
    MESSAGE_LIST_UPDATE_SUCCESS: 'MESSAGE_LIST_UPDATE_SUCCESS',
    MESSAGE_LIST_UPDATE_FAILURE: 'MESSAGE_LIST_UPDATE_FAILURE',
})